### ISSUE TITLE
Better image

### ISSUE THREAD

**Issue by E5ten** [SSStormy/mpd-rich-presence-discord#3]
The current image (just the word mpd) is pretty uninteresting, would it be possible to use something like the actual mpd logo instead? https://www.musicpd.org/logo.png

**Comment by SSStormy** [comment]
Discord requires that app images be larger than 512x512. If you could provide an image like that, I can work something out.

**Comment by E5ten** [comment]
https://www.flaticon.com/free-icon/compact-disc_148726#term=music&page=1&position=68 This is pretty good imo, it has a 512x512 png and just requires that you give credit to the author in the README, like this "Icon made by https://smashicons.com/ from www.flaticon.com". Like it?

**Comment by E5ten** [comment]
https://www.flaticon.com/free-icon/audio_419826 Maybe this represnets mpd better?

**Comment by simoniz0r** [comment]
FWIW, I've seen a few complaints about the default icon not looking so great... doesn't even really look like a media player icon.

**Comment by SSStormy** [comment]
Turns out that MPD's github repo has got an SVG of ther logo meaning we can resize it to 1024x1024: 
![mpd2](https://user-images.githubusercontent.com/10726335/39165868-1f31e5ea-4776-11e8-8143-55d57bedcebf.png)

I'm happy to change the app icon to this if people are up for it.

**Comment by NanoDrivee** [comment]
Yes, please do. That would be perfect.

**Comment by SSStormy** [comment]
OK all 3 apps should be using the new icon.

![2018-04-24-110538_274x285_scrot](https://user-images.githubusercontent.com/10726335/39180840-78de8cac-47a7-11e8-85cb-8aa02bebb932.png)

This means we need new images for the README Do you guys mind taking some and uploading them here?

**Comment by E5ten** [comment]
![mpdrpc1](https://user-images.githubusercontent.com/24554283/39184352-10827760-4791-11e8-9eff-525c7eb4986e.png)
![mpdrpc2](https://user-images.githubusercontent.com/24554283/39184415-48c08022-4791-11e8-8a52-610f57d7188f.png)
