### ISSUE TITLE
Detect discord-rpc installed to system and link dynamically to it

### ISSUE THREAD

**Issue by E5ten** [SSStormy/mpd-rich-presence-discord#4]
Is there a chance this will be possible? As dynamic linking is usually preferred.

**Comment by SSStormy** [comment]
Pushed some stuff to the reuse-so branch. CMake will now try to locate discord-rpc libs and headers. If it cannot find them, it'll build from source.

Before I merge this, I'd like you to try building the lib on the reuse-so branch check if the output of `ldd mpd_discord_richpresence` for `libdiscord-rpc.so` is the correct path to the discord-rpc lib installed at your system path.

**Comment by E5ten** [comment]
It points to the correct path thanks for the quick work :)
