### ISSUE TITLE
mpd-discord.service failing, failed with result 'dependency'

### ISSUE THREAD

**Issue by NanoDrivee** [SSStormy/mpd-rich-presence-discord#6]
Using the AUR package found here:
https://aur.archlinux.org/packages/mpd-rich-presence-discord-git/

PKGBUILD installs all the dependencies listed in the repo so I'm not sure why it would be missing any dependencies.

```May 26 09:35:16 Vanguard systemd[1]: Dependency failed for Discord Rich Presence for MPD.
-- Subject: Unit mpd-discord.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mpd-discord.service has failed.
-- 
-- The result is RESULT.
May 26 09:35:16 Vanguard systemd[1]: mpd-discord.service: Job mpd-discord.service/start failed with result 'dependency'.
May 26 09:35:16 Vanguard polkitd[483]: Unregistered Authentication Agent for unix-process:4220:195539 (system bus name```

**Comment by SSStormy** [comment]
The failing dependency here would be the systemd mpd service. Try enabling and then starting `mpd.service`.

After that you might run into an issue where the service cannot find the executable. I'll try to figure something out with the PKGBUILD maintainer. In the meanwhile, refer to my [comment](https://aur.archlinux.org/packages/mpd-rich-presence-discord-git) on the AUR package page for the workaround.

**Comment by SSStormy** [comment]
>After that you might run into an issue where the service cannot find the executable. I'll try to figure something out with the PKGBUILD maintainer. In the meanwhile, refer to my comment on the AUR package page for the workaround.

This should be fixed now. I'd love to hear if everything works for you now.

**Comment by NanoDrivee** [comment]
It was because I was using `mpd.service --user`. Decided to forego using the `mpd-discord.service` and run it locally instead since mpd-rpc isn't something that should be running as root. Maybe `mpd-discord.service` would be better suited to use a --user service as well.

Thanks for the quick response time!

**Comment by SSStormy** [comment]
I just tested out mpd and mpd-discord-richpresence running as a user service and everything seems to be in order. You could try dropping the mpd-discord.service into `~/.config/systemd/user`, daemon-reload systemd and start mpd-discord as a user service.

**Comment by NanoDrivee** [comment]
Yep, that worked. Thanks again!
