### ISSUE TITLE
Don't broadcast when idle

### ISSUE THREAD

**Issue by OrdinaryMagician** [SSStormy/mpd-rich-presence-discord#8]
It seems kind of unnecessary to have a status set even when completely stopped, especially considering some of us pretty much have mpd running at all times even when not using it.

**Comment by SSStormy** [comment]
That's been there for a while now so I'm not going to remove it. How does a command line flag that stops the idle broadcasting sound?

**Comment by OrdinaryMagician** [comment]
That would be fine.

**Comment by SSStormy** [comment]
dee083e7fbb4a69c8847c420ea2fe044a0e38f4b adds the `--no-idle` flag, try it out.

**Comment by OrdinaryMagician** [comment]
Seems to work alright over here.
